# Exercices NumPy 

<span style="color:red">Réalisation de tous les exercices sans utiliser de boucles.</span>
---

In [1]:
import numpy as np

# Configuration de la précision d'affichage
np.set_printoptions(precision=2, suppress=True)
print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## Exercice 1 : Création et restructuration d'un tableau (1D → 2D)

**Objectif :**
1. Créez un vecteur 1D contenant les entiers de 1 à 20.
2. Transformez-le en une matrice 2D de dimensions $4 \times 5$.

In [21]:
# VOTRE CODE ICI
import numpy as np

v = np.arange(1,21)
print(v)
#print(v[::-1])

t = v.reshape(4,5)
print(t)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Exercice 2 : Extraction par masque booléen (1D)

**Objectif :**
Soit un vecteur 1D de 15 nombres aléatoires entre 0 et 50. Extrayez tous les éléments strictement supérieurs à 25 **ET** pairs.

In [37]:

# VOTRE CODE ICI

import numpy as np


v = np.random.randint(0, 51, size=15)
sup = v[(v>25) & (v%2 == 0)]
print(sup)


[30 34 50 46 38]


## Exercice 3 : Inversion et inversion par colonnes (1D et 2D)

**Objectif :**
1. Inversez l'ordre des éléments d'un vecteur 1D de taille 10.
2. Soit une matrice $4 \times 4$, inversez l'ordre de ses colonnes (la dernière colonne devient la première).

In [ ]:
# VOTRE CODE ICI
import numpy as np

v = np.arange(1,11)
inv = v[::-1]
print(inv)

v1 = np.arange(1,21)

vd = v1.reshape(4,5)
vd1 = np.fliplr(vd) 
print(vd1)

[10  9  8  7  6  5  4  3  2  1]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


## Exercice 4 : Statistique par axe (2D)

**Objectif :**
Soit une matrice $5 \times 3$ d'entiers aléatoires entre 1 et 100.
1. Calculez la moyenne globale de la matrice.
2. Calculez la somme des éléments pour chaque **colonne**.
3. Obtenez la valeur maximale pour chaque **ligne**.

In [53]:
# VOTRE CODE ICI

import numpy as np

v = np.random.randint(1,100 , size=(5,3))
print(v)
moyen = v.mean()
print(moyen)
sum_clmn = v.sum(axis=0)
print(sum_clmn)
max_row = v.max(axis=1)
print(max_row)


[[97 60 40]
 [79 57 72]
 [70 65 59]
 [43 72  4]
 [63 67 43]]
59.4
[352 321 218]
[97 79 70 72 67]


## Exercice 5 : Remplacement des valeurs manquantes (1D / 2D)

**Objectif :**
Soit le tableau : `arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])`.
Remplacez toutes les valeurs `NaN` par la moyenne des valeurs non manquantes du tableau.

In [61]:
# VOTRE CODE ICI
import numpy as np

arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
print(arr)
mean = np.nanmean(arr)
arr[np.isnan(arr)] = mean
print(arr)

[ 1.  2. nan  4. nan  6.]
[1.   2.   3.25 4.   3.25 6.  ]


## Exercice 6 : Concaténation et empilement (2D)

**Objectif :**
Soit deux matrices $A$ et $B$ de dimensions $3 \times 2$.
1. Empilez-les verticalement pour obtenir une matrice $6 \times 2$.
2. Empilez-les horizontalement pour obtenir une matrice $3 \times 4$.

In [72]:
# VOTRE CODE ICI

import numpy as np

a = np.random.randint(1,10,size=(3,2))
b = np.random.randint(9,20,size=(3,2))
#print(a)
#print(b)

cv = np.vstack((a,b))
print(cv)
ch = np.hstack((a,b))
print(ch)

[[ 3  6]
 [ 3  5]
 [ 5  3]
 [19 11]
 [19 18]
 [12 16]]
[[ 3  6 19 11]
 [ 3  5 19 18]
 [ 5  3 12 16]]


## Exercice 7 : Recherche d'indices spécifiques (`np.where`) (1D)

**Objectif :**
Soit un vecteur 1D de 12 valeurs réelles. Récupérez les **indices** (et non les valeurs) de tous les éléments compris entre 10 et 20 inclus.

In [76]:
# VOTRE CODE ICI
import numpy as np

v = np.random.randint(1,50,size=(20))
print(v)

v1 = np.where((v>10) & (v<20))
print(v1)

[31 38 41 23 21 44 38 11  3 39 37 11 46 30 31 41 48 19 44 17]
(array([ 7, 11, 17, 19]),)


## Exercice 8 : Calcul de la diagonale et trace (2D)

**Objectif :**
Générez une matrice carrée $4 \times 4$ d'entiers.
1. Extrayez les éléments de la diagonale principale sous forme de vecteur 1D.
2. Calculez la somme de ces éléments (la trace) en utilisant la fonction NumPy dédiée.

In [81]:
# VOTRE CODE ICI
import numpy as np

v = np.random.randint(1,20,size=(4,4))
print(v)

dg = np.diag(v)
print(dg)

sum = np.sum(dg)
print(sum)

[[ 1 12 15 10]
 [17  8 11  9]
 [10  4 19  4]
 [ 2  7  9 19]]
[ 1  8 19 19]
47


## Exercice 9 : Masquage conditionnel & Remplacement rapide (1D)

**Objectif :**
Créez un vecteur 1D de 20 entiers aléatoires entre -10 et 10. Sans utiliser de boucle for ni d'instructions if, remplacez tous les nombres négatifs impairs par leur carré, et tous les nombres positifs pairs par 0.

In [87]:
# VOTRE CODE ICI

import numpy as np

v = np.random.randint(-10,10,size=20)
print(v)

v[(v < 0) & (v % 2 != 0)] = np.square(v[(v < 0) & (v % 2 != 0)])
v[(v >= 0) & (v % 2 != 0)] = np.square(v[(v >= 0) & (v % 2 != 0)])
print(v)

[ -3   1   0   3  -3   0  -3  -6  -4  -7  -4   4   5   6   4  -6 -10   8
  -5  -1]
[  81    1    0    9   81    0   81   -6   -4 2401   -4    4   25    6
    4   -6  -10    8  625    1]


## Exercice 10 : Extraction par glissement / Fenêtres glissantes (1D)

**Objectif :**
Soit un vecteur 1D $V = [1, 2, 3, 4, 5, 6, 7, 8]$. Générez une matrice 2D représentant toutes les sous-fenêtres glissantes de taille 3 avec un pas (stride) de 1.Résultat attendu :$$\begin{bmatrix} 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ \dots & \dots & \dots \end{bmatrix}$$

In [88]:
# VOTRE CODE ICI
import numpy as np

V = np.array([1, 2, 3, 4, 5, 6, 7, 8])

windows = np.lib.stride_tricks.sliding_window_view(V, 3)

print(windows)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


## Exercice 11 : Extraction des k plus grands éléments par ligne (2D)

**Objectif :**
Soit une matrice 2D de dimensions $6 \times 8$ remplie d'entiers aléatoires. Extrayez, pour chaque ligne, les 3 plus grandes valeurs et leurs indices respectifs, triés par ordre décroissant.

In [90]:
# VOTRE CODE ICI

import numpy as np

v = np.random.randint(1,10,size=(6,8))
print(v)



idx = np.argsort(v, axis=1)[:, -3:][:, ::-1]

values = np.take_along_axis(v, idx, axis=1)

print("Inndices :")
print(idx)

print("Values :")
print(values)


[[7 2 7 8 7 1 9 2]
 [3 2 1 8 7 3 1 6]
 [4 9 9 1 8 9 3 6]
 [4 9 6 5 6 2 2 3]
 [9 3 5 4 3 4 2 2]
 [6 9 1 1 5 2 3 9]]
Inndices :
[[6 3 2]
 [3 4 7]
 [5 2 1]
 [1 4 2]
 [0 2 5]
 [7 1 0]]
Values :
[[9 8 7]
 [8 7 6]
 [9 9 9]
 [9 6 6]
 [9 5 4]
 [9 9 6]]
